function languageChinese(){
	this.time = "时间";
	this.speed = "速度";
	this.licheng = "里程"
	this.close = "关闭";
	this.addPoint = "添加自定义点";
	this.addRectangle = "添加矩形";
	this.addPolygon = "添加多边形";
	this.addLine = "添加线路";
	this.btnSearch = "搜索";
	this.tipAddRectangle = "拉框绘制矩形";
	this.tipAddPolygon = "双击结束";
	this.tipAddPoint = "单击添加自定义点";
	this.tipAddLine = "双击结束";
	this.tipSearch = "拉框搜索";
	this.fullScreen = "地图全屏";
	this.fullScreenExit = "退出全屏";
	this.btnCenter = "设置当前地图位置为默认位置";
	this.expand = "展开";
	this.expandExit = "收缩";
	this.mapBaidu = "百度地图";
	this.mapGoogle = "谷歌地图";
	this.mapMapInfo = "MapInfo地图";
	this.mapArcGis = "ArcGis";
	this.mapMapBar = "四维地图";
	this.mapAddress = "地址";
	this.tipZoomIn = "拉框放大";
	this.tipZoomOut = "拉框缩小";
	this.tipAddCircle = "添加圆形";
	this.tipDistance = "测量距离";
	this.tipCountry = "全国";
	this.tipArea = "测量面积";
	this.tipCruise = "漫游";
	this.tipPrint = "打印";
	this.tipCapture = "截图";
}

function languageTw(){
	this.time = "時間";
	this.speed = "速度";
	this.licheng = "裏程"
	this.close = "關閉";
	this.addPoint = "添加自定義點";
	this.addRectangle = "添加矩形";
	this.addPolygon = "添加多邊形";
	this.addLine = "添加線路";
	this.btnSearch = "搜索";
	this.tipAddRectangle = "拉框繪制矩形";
	this.tipAddPolygon = "雙擊結束";
	this.tipAddPoint = "單擊添加自定義點";
	this.tipAddLine = "雙擊結束";
	this.tipSearch = "拉框搜索";
	this.fullScreen = "地圖全屏";
	this.fullScreenExit = "退出全屏";
	this.btnCenter = "設置當前地圖位置爲默認位置";
	this.expand = "展開";
	this.expandExit = "收縮";
	this.mapBaidu = "百度地圖";
	this.mapGoogle = "谷歌地圖";
	this.mapMapInfo = "MapInfo地圖";
	this.mapArcGis = "ArcGis";
	this.mapMapBar = "四維地圖";
	this.mapAddress = "地址";
	this.tipZoomIn = "拉框放大";
	this.tipZoomOut = "拉框缩小";
	this.tipAddCircle = "添加圆形";
	this.tipDistance = "測量距離";
	this.tipCountry = "全國";
	this.tipArea = "測量面積";
	this.tipCruise = "漫遊";
	this.tipPrint = "打印";
	this.tipCapture = "截圖";
}

function languageEnglish(){
	this.time = "Time";
	this.speed = "Speed";
	this.licheng = "Distance"
	this.close = "Close";
	this.addPoint = "Add Custom Point";
	this.addRectangle = "Add Rectangle";
	this.addPolygon = "Add Polygon";
	this.addLine = "Add Line";
	this.btnSearch = "Search";
	this.tipAddRectangle = "Pull Dox Draw Rectangle";
	this.tipAddPolygon = "Double-Click End";
	this.tipAddPoint = "Click Add Custom Point";
	this.tipAddLine = "Double-Click End";
	this.tipSearch = "Search Draw Rectangle";
	this.fullScreen = "Map Full Screen";
	this.fullScreenExit = "Full Screen Exit";
	this.btnCenter = "Set curress map information is default map information.";
	this.expand = "Expand";
	this.expandExit = "Collapse";
	this.mapBaidu = "Baidu Map";
	this.mapGoogle = "Google Map";
	this.mapMapInfo = "MapInfo";
	this.mapArcGis = "ArcGis Map";
	this.mapMapBar = "Mapbar";
	this.mapAddress = "Address";
	this.tipZoomIn = "Pull Box Enlarge";
	this.tipZoomOut = "Pull box to narrow down";
	this.tipAddCircle = "Add Circle";
	this.tipDistance = "Measure Distance";
	this.tipCountry = "National";
	this.tipArea = "Measure area";
	this.tipCruise = "Odyssey";
	this.tipPrint = "Print";
	this.tipCapture = "Shot";
}

function languageArabic(){
	this.time = "وقت";
	this.speed = "السرعة";
	this.licheng = "مسافة"
	this.close = "قريب";
	this.addPoint = "إضافة مخصص نقطة";
	this.addRectangle = "إضافة مستطيل";
	this.addPolygon = "إضافة مضلع";
	this.addLine = "إضافة لاين";
	this.btnSearch = "بحث";
	this.tipAddRectangle = "سحب دوكس رسم مستطيل";
	this.tipAddPolygon = "انقر نقرا مزدوجا فوق النهاية";
	this.tipAddPoint = "انقر فوق إضافة مخصص نقطة";
	this.tipAddLine = "انقر نقرا مزدوجا فوق النهاية";
	this.tipSearch = "البحث رسم مستطيل";
	this.fullScreen = "خريطة الشاشة الكاملة";
	this.fullScreenExit = "خروج كامل الشاشة";
	this.btnCenter = "تعيين معلومات الخريطة هي المعلومات curress الخريطة الافتراضية.";
	this.expand = "وسع";
	this.expandExit = "انهيار";
	this.mapBaidu = "بايدو خريطة";
	this.mapGoogle = "خريطة جوجل";
	this.mapArcGis = "ArcGis Map";
	this.mapMapBar = "Mapbar";
	this.mapMapInfo = "MapInfo";
	this.mapAddress = "عنوان";
	this.tipZoomIn = "مربع سحب تكبير";
	this.tipZoomOut = "مربع سحب لتضييق";
	this.tipAddCircle = "إضافة جولة";
	this.tipDistance = "قياس المسافة";
	this.tipCountry = "على الصعيد الوطني";
	this.tipArea = "منطقة القياس";
	this.tipCruise = "تجوال";
	this.tipPrint = "طباعة";
	this.tipCapture = "لقطة";
}

function languagePortugues(){
	this.time = "Hora";
	this.speed = "Velocidade";
	this.licheng = "Distancia"
	this.close = "fechar";
	this.addPoint = "Adicionar Ponto Personalizado"; 
	this.addRectangle = "Adicionar Retângulo"; 
	this.addPolygon = "Adicionar polígono"; 
	this.addLine = "Adicionar Linha";
	this.btnSearch = "Pesquisar"; 
	this.tipAddRectangle = "Puxe Dox Desenhar Retângulo"; 
	this.tipAddPolygon = "Duplo-Clique End"; 
	this.tipAddPoint = "Clique em Adicionar Ponto Personalizado"; 
	this.tipSearch = "Procurar Desenhar Retângulo"; 
	this.tipAddLine = "Duplo-Clique em Finalizar";
	this.fullScreen = "Mapa de tela cheia"; 
	this.fullScreenExit = "Sair da tela inteira"; 
	this.btnCenter = "Definir informações do mapa curress é a informação padrão do mapa.";
	this.expand = "Expandir"; 
	this.expandExit = "Fechar"; 
	this.mapBaidu = "Baidu Mapa"; 
	this.mapGoogle = "Google Map"; 
	this.mapMapInfo = "MapInfo";
	this.mapArcGis = "ArcGis Map";
	this.mapMapBar = "Mapbar";
	this.mapAddress = "endereço";
	this.tipZoomIn = "Caixa Pull Ampliar";
	this.tipZoomOut = "Puxe Caixa Para Diminuir";
	this.tipAddCircle = "Adicionar Redonda";
	this.tipDistance = "Medir A Distância";
	this.tipCountry = "Nacional";
	this.tipArea = "área de medição";
	this.tipCruise = "Odyssey";
	this.tipPrint = "Print";
	this.tipCapture = "Shot";
}

function languageSpanish(){
	this.time = "Tiempo"; 
	this.speed = "Velocidad"; 
	this.licheng = "Distancia" 
	this.Close = "Cerrar"; 
	this.addPoint = "Añadir Punto Custom"; 
	this.addRectangle = "Añadir Rectángulo"; 
	this.addPolygon = "Añadir Polígono"; 
	this.addLine = "Añadir línea"; 
	this.btnSearch = "Buscar"; 
	this.tipAddRectangle = "Tire Dox Draw Rectangle"; 
	this.tipAddPolygon = "Haga doble clic End"; 
	this.tipAddPoint = "Haga clic en Agregar Point Custom"; 
	this.tipAddLine = "Haga doble clic en End"; 
	this.tipSearch = "Buscar Dibujar Rectángulo"; 
	this.fullScreen = "Mapa en pantalla completa"; 
	this.fullScreenExit = "Salir de pantalla completa"; 
	this.btnCenter = "Configurar la información del mapa es curress información predeterminada mapa."; 
	this.expand = "Expandir"; 
	this.expandExit = "Collapse"; 
	this.mapBaidu = "Baidu mapa"; 
	this.mapGoogle = "Google Map"; 
	this.mapMapInfo = "MapInfo";
	this.mapArcGis = "ArcGis Map";
	this.mapMapBar = "Mapbar";
	this.mapAddress = "Dirección";
	this.tipZoomIn = "Caja De Acceso Agrandar";
	this.tipZoomOut = "Caja Tire De Restringir";
	this.tipAddCircle = "Añadir Ronda";
	this.tipDistance = "Medir La Distancia";
	this.tipCountry = "Nacional";
	this.tipArea = "área de medición";
	this.tipCruise = "Odyssey";
	this.tipPrint = "Print";
	this.tipCapture = "Tiro";
}

function languageTurkey(){
	this.time = "Zaman";
	this.speed = "Hız";
	this.licheng = "Kilometre"
	this.close = "Kapalı";
	this.addPoint = "Müşteri Noktası ekle";
	this.addRectangle = "Genişletme ekle";
	this.addPolygon = "Poligon ekle";
	this.addLine = "Add Line";
	this.btnSearch = "Arama";
	this.tipAddRectangle = "Dikdörkeni çekme";
	this.tipAddPolygon = "iki kez tıkla";
	this.tipAddPoint = "Müşteri noktsı eklemek için tıkla";
	this.tipAddLine = "Double-Click End";
	this.tipSearch = "Dikdörtken çekme ara";
	this.fullScreen = "Tam Ekran Harita";
	this.fullScreenExit = "tAM eKRANDAN çIK";
	this.btnCenter = "Set curress map information is default map information.";
	this.expand = "Genişletmek";
	this.expandExit = "Yığılma";
	this.mapBaidu = "Harita Baidu";
	this.mapGoogle = "Harita Google";
	this.mapMapInfo = "MapInfo";
	this.mapArcGis = "ArcGis Map";
	this.mapMapBar = "Mapbar";
	this.mapAddress = "adres";
	this.tipZoomIn = "Çekme Kutusu Büyüt";
	this.tipZoomOut = "Daraltmak için kutuyu çekin";
	this.tipAddCircle = "Yuvarlak Ekle";
	this.tipDistance = "Mesafeyi ölçün";
	this.tipCountry = "Ulusal";
	this.tipArea = "ölçüm alanı";
	this.tipCruise = "Odyssey";
	this.tipPrint = "Print";
	this.tipCapture = "Atış";
}

function languageThai() {
	this.time = "เวลา";
	this.speed = "ความเร็ว";
	this.licheng = "ระยะทาง"
	this.close = "ใกล้";
	this.addPoint = "เพิ่มจุดที่กำหนด";
	this.addRectangle = "เพิ่มสี่เหลี่ยมผืนผ้า";
	this.addPolygon = "เพิ่มรูปหลายเหลี่ยม";
	this.addLine = "เพิ่มสาย";
	this.btnSearch = "ค้นหา";
	this.tipAddRectangle = "Pull Dox วาดสี่เหลี่ยมผืนผ้า ";
	this.tipAddPolygon = "ดับเบิลคลิกที่สุดท้าย";
	this.tipAddPoint = "คลิกเพิ่มจุดที่กำหนด";
	this.tipAddLine = "ดับเบิลคลิกที่สุดท้าย";
	this.tipSearch = "ค้นหาวาดสี่เหลี่ยมผืนผ้า";
	this.fullScreen = "แผนที่เต็มหน้าจอ";
	this.fullScreenExit = "ออกเต็มหน้าจอ";
	this.btnCenter = "ตั้งค่าข้อมูลแผนที่ curress เป็นข้อมูลแผนที่ที่เป็นค่าเริ่มต้น";
	this.expand = "ขยายความ";
	this.expandExit = "ล่มสลาย";
	this.mapBaidu = "Baidu Map";
	this.mapGoogle = "Google Map";
	this.mapMapInfo = "MapInfo";
	this.mapArcGis = "ArcGis Map";
	this.mapMapBar = "Mapbar";
	this.mapAddress = "ที่อยู่";
	this.tipZoomIn = "ดึงกล่องขนาดใหญ่";
	this.tipZoomOut = "ดึงกล่องให้แคบลง";
	this.tipAddCircle = "เพิ่มรอบ";
	this.tipDistance = "วัดระยะทาง";
	this.tipCountry = "แห่งชาติ";
	this.tipArea = "พื้นที่วัด";
	this.tipCruise = "Odyssey";
	this.tipPrint = "พิมพ์";
	this.tipCapture = "ยิง";
}

function languageBulgarian() {
	this.time = "Час";
	this.speed = "Скорост";
	this.licheng = "Разстояние";
	this.close = "Затвори";
	this.addPoint = "Добави точка";
	this.addRectangle = "Добави правоъгълник";
	this.addPolygon = "Добави регион";
	this.addLine = "Добави линия";
	this.btnSearch = "Търсене";
	this.tipAddRectangle = "С издърпване направете правоъгълник";
	this.tipAddPolygon = "Два клика за край";
	this.tipAddPoint = "Един клик за добавяне на точка";
	this.tipAddLine = "Два клика за край";
	this.tipSearch = "Търсене на правоъгълник";
	this.fullScreen = "Карта на цял екран";
	this.fullScreenExit = "Изход от цял екран";
	this.btnCenter = "Запазете текущата карта като карта по подразбиране.";
	this.expand = "Разпъване";
	this.expandExit = "Свиване";
	this.mapBaidu = "Baidu карта";
	this.mapGoogle = "Google карта";
	this.mapMapInfo = "MapInfo карта";
	this.mapArcGis = "ArcGis карта";
	this.mapMapBar = "Mapbar";
	this.mapAddress = "Адрес";
	this.tipZoomIn = "дърпане кутия мащабиране";
	this.tipZoomOut = "дърпане кутия, за да стесните";
	this.tipAddCircle = "Добави кръг";
	this.tipDistance = "мярка разстояние";
	this.tipCountry = "национална";
	this.tipArea = "измерване зона";
	this.tipCruise = "Odyssey";
	this.tipPrint = "печат";
	this.tipCapture = "изстрел";
}